<a href="https://colab.research.google.com/github/agulhane090398/PythonViz/blob/main/NPS_Casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Case Study : NPS**

In [ ]:
import numpy as np
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
# or else download it from the link and direcly paste in colab

Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

but Gdown can't. Please check connections and permissions.


## *Lets load the data*

In [ ]:
score=np.loadtxt('survey.txt', dtype='int')

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
print(score.shape)
print(score.ndim)
print(score.min)
print(score.max)

(1167,)
1
<built-in method min of numpy.ndarray object at 0x7d37ea48a0d0>
<built-in method max of numpy.ndarray object at 0x7d37ea48a0d0>


Now, let's calculate NPS using these response.

NPS = % Promoters - % Detractors

Now, in order to calculate NPS, we need to calculate two things:

 * % Promoters
 * % Detractors

Similarly, We will map our scores into 3 categories s.t:

*  0 - 6: Detractors

* 7 - 8: Passive

* 9 - 10: Prometers

This process is called binning

In [ ]:
total=score.shape[0]

In [ ]:
detractor=score[score<=6].shape[0]

In [ ]:
percentDetractor=detractor/total*100
percentDetractor

28.449014567266495

In [ ]:
promoter=score[score>=9].shape[0]
percentPromoter=promoter/total*100
percentPromoter

52.185089974293064

In [ ]:
# So,
nps=percentPromoter-percentDetractor
nps

23.73607540702657

### Now bining the data

In [ ]:
arr=np.empty(shape=score.shape, dtype='U20')

In [ ]:
arr[score<=6]='Detractors'
arr

array(['', '', 'Detractors', ..., 'Detractors', '', ''], dtype='<U20')

In [ ]:
# similarly
arr[(score<=8) & (score>=7)]="Passive"
arr

array(['Passive', '', 'Detractors', ..., 'Detractors', '', ''],
      dtype='<U20')

In [ ]:
arr[score>=9]="Promoters"
arr

array(['Passive', 'Promoters', 'Detractors', ..., 'Detractors',
       'Promoters', 'Promoters'], dtype='<U20')

### Count for each category

In [ ]:
promoter_count=arr[arr=="Promoters"].shape[0]
promoter_count

609

In [ ]:
detrator_count=arr[arr=="Detractors"].shape[0]
detrator_count

332

In [ ]:
passive_count=arr[arr=="Passive"].shape[0]
passive_count

226

In [ ]:
# similary  we can also do:-

np.unique(arr, return_counts=True)

(array(['Detractors', 'Passive', 'Promoters'], dtype='<U20'),
 array([332, 226, 609]))

In [ ]:
unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)

['Detractors' 'Passive' 'Promoters']
[332 226 609]
